name: .NET Core CI

on:
  push:
    paths:
      - 'ip-registry-client/**'
  pull_request:
    paths:
      - 'ip-registry-client/**'

jobs:
  build-dotnet:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./ip-registry-client/core_web/core_web.csproj

    - name: Build
      run: dotnet build ./ip-registry-client/core_web/core_web.csproj --no-restore --configuration Release

    - name: Run tests
      run: dotnet test ./ip-registry-client/ip-registry-client.sln --no-build --configuration Release --logger "trx"
